### ISSUE TITLE
error running the demo

### ISSUE THREAD

**Issue by kais85** [karShetty/PLIKS#1]
Hi
thanks for sharing the code, 
when i try to run the demo as instructed i'm getting the following error 

```
Traceback (most recent call last):
  File "demo.py", line 276, in <module>
    demo.vis_step(path)
  File "demo.py", line 122, in vis_step
    pred_pose_anal, pred_beta_anal, trans_pred_anal, K_ = self.pliks(pred_smpl_uvd.float(),
  File "/home/end-user/miniconda3/envs/plkis/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/end-user/kais/experiments/PLIKS/pliks/model/PLIKS.py", line 162, in forward
    H = A_c.permute(0, 2, 1).bmm(B_c)
RuntimeError: self dim 0 must match batch2 dim 0 
```

any idea what could be causing this error 

Thanks

**Comment by karShetty** [comment]
Hi,  my best guess from the error message would be that you are using `basicModel_neutral_lbs_10_207_0_v1.1.0.pkl` (300 shape components) instead of `basicModel_neutral_lbs_10_207_0_v1.0.0.pkl` (10 shape components). Make sure to use the model with 10 components or modify to `shapedirs` to accept only the first10 components`np.array(smpl_model['shapedirs']))[...,:10]`
